import { ChangeEvent, useEffect, useState } from "react";
import { Cards, FormField } from "../components";

const Home = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [allPosts, setAllPosts] = useState<any>([]);

  const [searchText, setSearchText] = useState<string>("");
  const [searchResults, setSearchResults] = useState<any>([]);
  const [searchTimeout, setSearchTimeout] = useState<any>(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);

      try {
        const response = await fetch("https://picassoai-server.onrender.com/api/v1/posts", {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });

        if (response.ok) {
          const result = await response.json();
          setAllPosts(result.data.reverse());
        }
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    };
    fetchPosts();
  }, []);

  const handleSearchChange = (e: ChangeEvent<HTMLInputElement>) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResults = allPosts.filter(
          (post: any) =>
            post.name.toLowerCase().includes(searchText.toLowerCase()) ||
            post.prompt.toLowerCase().includes(searchText.toLowerCase())
        );
        setSearchResults(searchResults);
      }, 500)
    );
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-gray-700 text-3xl">
          The Community Showcase
        </h1>
        <p className="mt-2 text-gray-400 text-base">
          Browse through a collection of imaginative and visually stunning
          images generated by OpenAI
        </p>
      </div>
      <div className="mt-16">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search something..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <img src="./rings.svg" className="h-24" />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-gray-500 text-xl mb-3">
                Showing Results for &nbsp;
                <span className="text-gray-800">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <Cards data={searchResults} title="No results" />
              ) : (
                <Cards data={allPosts} title="No post" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
