import { useState } from "react";
import { Cards, FormField } from "../components";
import Loader from "../components/Loader";

const Home = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [allPosts, setAllPosts] = useState<any>([]);

  const [searchText, setSearchText] = useState<string>("s");

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-gray-700 text-3xl">
          The Community Showcase
        </h1>
        <p className="mt-2 text-gray-400 text-base">
          Browse through a collection of imaginative and visually stunning
          images generated by OpenAI
        </p>
      </div>
      <div className="mt-16">
        {/* <FormField /> */}
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && <p>Search results for {searchText}</p>}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <Cards data={[]} title="No results" />
              ) : (
                <Cards data={[]} title="no post" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
